spring:
  kafka:
    bootstrap-servers: pkc-312o0.ap-southeast-1.aws.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='LK2WG55445KOLBYS' password='Bx9Y30C5jHwC4pNti3CQ+ApbvFHYNeU+c3HyaRJu19eXe2jJmYAV9cf/Lk2407cO';
        mechanism: PLAIN
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: LM7UEIBXCVBWE7CP:qMKnbwQqgILSebidVjgoZgPXCnXhif5W/fPnA7zC1Bi8aKqYvNVVQiMdxsVXfb0i
      schema:
        registry:
          url: https://psrc-7yzmzo.ap-southeast-1.aws.confluent.cloud
    producer:
      client-id: team1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
